version: '3.8'

services:
  sso-service:
    image: sso-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sso_service
    ports:
      - "7072:8080"
    environment:
      - ConnectionStrings__SSODatabase=Server=host.docker.internal,1433;Database=SSO_DB;User Id=sa;Password=uni;TrustServerCertificate=true;MultipleActiveResultSets=True
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped