services:
  app:
    image: envio_correo_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: envio_correo_app
    ports:
      - "7069:8080"
    environment:
      - ConnectionStrings__UniversidadConnection=Server=host.docker.internal\SQLNET;Database=GestionMatriculaDB;User Id=sa;Password=uni;TrustServerCertificate=true;MultipleActiveResultSets=True
      - DOTNET_RUNNING_IN_CONTAINER=true
      - KafkaApiBaseUrl=http://host.docker.internal:7070
      - RabbitMQApiBaseUrl=http://host.docker.internal:7080  # Nueva variable
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  rabbitmq_data: